version: "2"
volumes:
  spotify-cache:
services:
  island:
    build: ./island
    ports:
      - "80:80"
    privileged: true
    labels:
      io.balena.features.supervisor-api: '1'
    environment:
      BYF_API_URL: https://funky-monitor-neat.ngrok-free.app
      ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      BYF_USER: milan@backyardfoods.com
      BYF_PW: testtest
  porchlight:
    build: ./porchlight
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1
    environment:
      CEILING_LIGHT_GPIO_PIN: 6
  wave:
    build: ./wave
    restart: always
    privileged: true
    volumes:
      - spotify-cache:/spotify-cache
  label-printer:
    build: ./label-printer
    restart: always
    privileged: true
    labels:
      io.balena.features.supervisor-api: '1'
  receipt-printer:
    build: ./receipt-printer
    restart: always
    privileged: true
    labels:
      io.balena.features.supervisor-api: '1'
    environment:
      RECEIPT_PRINTER_KIOSK: true
#  baywatch:
#    build: ./baywatch
#    restart: always
#    privileged: true
#    environment:
#      BYF_API_URL: http://192.168.0.146:54321
# papertrail:
#   build: './papertrail'
#   restart: always
#   labels:
#     io.balena.features.supervisor-api: 1
#     io.balena.features.journal-logs: 1
#   environment:
#     PAPERTRAIL_TOKEN: d2B1ZzLuVYyi8uht9IgpuE9i_sN4
  reaper:
    build: ./reaper
    restart: always
    privileged: true
    labels:
      io.balena.features.supervisor-api: '1'
    environment:
      SCHEDULED_REBOOT_TIME_UTC: '10:00'
#  wifi-connect:
#    build: ./wifi-connect
#    network_mode: "host"
#    labels:
#      io.balena.features.dbus: '1'
#    cap_add:
#      - NET_ADMIN
#    environment:
#      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"